# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-19 02:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('summary', models.TextField()),
                ('example_usage', models.TextField()),
                ('example_output', models.TextField()),
                ('author', models.CharField(max_length=128)),
                ('download_link', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='NseArgv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('argv', models.CharField(blank=True, max_length=128)),
                ('argv_discription', models.TextField(blank=True)),
                ('script', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Nse')),
            ],
        ),
        migrations.CreateModel(
            name='NseCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categories', models.CharField(choices=[('auth', 'auth'), ('broadcast', 'broadcast'), ('brute', 'brute'), ('default', 'default'), ('discovery', 'discovery'), ('dos', 'dos'), ('exploit', 'exploit'), ('external', 'external'), ('fuzzer', 'fuzzer'), ('intrusive', 'intrusive'), ('malware', 'malware'), ('safe', 'safe'), ('version', 'version'), ('vuln', 'vuln')], max_length=128)),
            ],
        ),
        migrations.AddField(
            model_name='nse',
            name='argvs',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arguments', to='api.NseArgv'),
        ),
        migrations.AddField(
            model_name='nse',
            name='categories',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categorie', to='api.NseCategory'),
        ),
    ]
