# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-19 03:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20160119_0304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nse',
            name='categories',
            field=models.CharField(choices=[('auth', 'auth'), ('broadcast', 'broadcast'), ('brute', 'brute'), ('default', 'default'), ('discovery', 'discovery'), ('dos', 'dos'), ('exploit', 'exploit'), ('external', 'external'), ('fuzzer', 'fuzzer'), ('intrusive', 'intrusive'), ('malware', 'malware'), ('safe', 'safe'), ('version', 'version'), ('vuln', 'vuln')], max_length=128),
        ),
    ]
