# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-19 03:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20160119_0327'),
    ]

    operations = [
        migrations.AddField(
            model_name='nse',
            name='summary_ja',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='nseargv',
            name='argv_discription_ja',
            field=models.TextField(blank=True),
        ),
    ]
