# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-19 04:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20160119_0331'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nse',
            old_name='categories',
            new_name='category',
        ),
    ]
