# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-19 05:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20160119_0432'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nseargv',
            old_name='argv_discription',
            new_name='argv_description',
        ),
        migrations.RenameField(
            model_name='nseargv',
            old_name='argv_discription_ja',
            new_name='argv_description_ja',
        ),
    ]
