# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-19 10:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20160119_0541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nse',
            name='argvs',
            field=models.ManyToManyField(blank=True, to='api.NseArgv'),
        ),
        migrations.AlterField(
            model_name='nse',
            name='example_output',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='nse',
            name='example_usage',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='nse',
            name='summary',
            field=models.TextField(blank=True),
        ),
    ]
