# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-20 00:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20160119_1041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nse',
            name='author',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='nse',
            name='download_link',
            field=models.URLField(blank=True),
        ),
    ]
