# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-20 00:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20160120_0011'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nse',
            options={'ordering': ['Nse__argvs']},
        ),
    ]
