# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-20 00:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20160120_0019'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nse',
            options={},
        ),
    ]
